<?php

/**
 * @file
 * Contains casestudies2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function casestudies2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the casestudies2 module.
    case 'help.page.casestudies2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }

  /**
   * Implements hook_form_alter() on behalf of casestudies.module.
   */
  function casestudies2_form_alter(&$form, FormStateInterface $form_state, $form_id) {
      // Change form id here
      if ($form_id == 'form_test_alter_form') {
          drupal_set_message('form_test_form_alter() executed.');

      }
}
